name: Validate

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "plugin"
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
